config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  resources :quotes
  resources :componentes_plans
  resources :atributos_componentes
  resources :images
  resources :atributos
  resources :tipo_atributos
  resources :componentes
  resources :sedes
  resources :conditions
  resources :formas_de_pagos
  resources :components
  resources :constructions
  resources :locations
  resources :supports
  resources :espacios
  resources :burial_services
  resources :anforas
  resources :servicio_de_cinerarios
  resources :traslados
  resources :velatorios
  resources :urnas
  resources :directions
  resources :plans
  resources :conditions
  resources :tipo_clientes
  resources :type_plans
  resources :publications
  resources :type_publications
  resources :roles
  resources :servicios
  resources :componentes
  resources :caracteristicas
  resources :telefonos
  resources :tipo_empresas
  resources :comunas
  resources :regions
  resources :empresas
  devise_for :usuarios, :controllers => { :registrations => 'registrations'}
  resources :usuario, :controller => "usuario"
  get '/usuarios/new'


  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anfora.rb
class Anfora < ApplicationRecord
end

app/models/atributo.rb
class Atributo < ApplicationRecord
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :urna
  belongs_to :velatorio
  belongs_to :traslado
  belongs_to :servicio_de_cinerario
  belongs_to :anfora
  belongs_to :burial_service
  belongs_to :espacio
  belongs_to :construction
  belongs_to :location
  belongs_to :support
  belongs_to :plan
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  belongs_to :region
  has_many :sedes
end

app/models/contacto.rb
class Contacto < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	belongs_to :tipo_empresa
	has_many :plans
	has_many :sedes
	belongs_to :usuario

	has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/espacio.rb
class Espacio < ApplicationRecord
end

app/models/formas_de_pago.rb
class FormasDePago < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :componente
  belongs_to :plan

  has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :servicio, optional: true
  belongs_to :type_plan
  belongs_to :tipo_cliente
  belongs_to :empresa
  has_many :componentes_plans
  has_many :componentes
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :plan
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/sede.rb
class Sede < ApplicationRecord
  belongs_to :empresa
  belongs_to :comuna
end

app/models/servicio.rb
class Servicio < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
  belongs_to :sede
end

app/models/traslado.rb
class Traslado < ApplicationRecord
end

app/models/urna.rb
class Urna < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessible :name, :apellido, :email, :password, :password_confirmation, :remember_me, :role_id
  belongs_to :role

end

app/controllers/formas_de_pagos_controller.rb
class FormasDePagosController < ApplicationController
  before_action :set_formas_de_pago, only: [:show, :edit, :update, :destroy]

  # GET /formas_de_pagos
  # GET /formas_de_pagos.json
  def index
    @formas_de_pagos = FormasDePago.all
  end

  # GET /formas_de_pagos/1
  # GET /formas_de_pagos/1.json
  def show
  end

  # GET /formas_de_pagos/new
  def new
    @formas_de_pago = FormasDePago.new
  end

  # GET /formas_de_pagos/1/edit
  def edit
  end

  # POST /formas_de_pagos
  # POST /formas_de_pagos.json
  def create
    @formas_de_pago = FormasDePago.new(formas_de_pago_params)

    respond_to do |format|
      if @formas_de_pago.save
        format.html { redirect_to @formas_de_pago, notice: 'Formas de pago was successfully created.' }
        format.json { render :show, status: :created, location: @formas_de_pago }
      else
        format.html { render :new }
        format.json { render json: @formas_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formas_de_pagos/1
  # PATCH/PUT /formas_de_pagos/1.json
  def update
    respond_to do |format|
      if @formas_de_pago.update(formas_de_pago_params)
        format.html { redirect_to @formas_de_pago, notice: 'Formas de pago was successfully updated.' }
        format.json { render :show, status: :ok, location: @formas_de_pago }
      else
        format.html { render :edit }
        format.json { render json: @formas_de_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formas_de_pagos/1
  # DELETE /formas_de_pagos/1.json
  def destroy
    @formas_de_pago.destroy
    respond_to do |format|
      format.html { redirect_to formas_de_pagos_url, notice: 'Formas de pago was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formas_de_pago
      @formas_de_pago = FormasDePago.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formas_de_pago_params
      params.require(:formas_de_pago).permit(:nombre)
    end
end

app/helpers/formas_de_pagos_helper.rb
module FormasDePagosHelper
end

app/views/formas_de_pagos/_form.html.erb
<%= form_for(formas_de_pago) do |f| %>
  <% if formas_de_pago.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formas_de_pago.errors.count, "error") %> prohibited this formas_de_pago from being saved:</h2>

      <ul>
      <% formas_de_pago.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, "Nombre:" %>
    <%= f.text_field :nombre, class:"form-control" %>  
  </div>

  <div class="actions">
    <%= f.submit "Crear Formas de Pago", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/formas_de_pagos/edit.html.erb
<div class="container">
	<h1>Editando Formas De Pago</h1>

	<%= render 'form', formas_de_pago: @formas_de_pago %>

	<%= link_to 'Ver', @formas_de_pago, class: "btn btn-default" %>
	<%= link_to 'Atrás', formas_de_pagos_path, class: "btn btn-danger" %>
</div>

app/views/formas_de_pagos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Formas De Pagos</h1>

  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @formas_de_pagos.each do |formas_de_pago| %>
        <tr>
          <td><%= formas_de_pago.nombre %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <% if usuario_signed_in? %>
              <% if Usuario.last.role_id == 2 %>
                <td><%= link_to 'Ver', formas_de_pago, class: "btn btn-primary" %></td>
                <td><%= link_to 'Editar', edit_formas_de_pago_path(formas_de_pago), class: "btn btn-success" %></td>
                <td><%= link_to 'Eliminar', formas_de_pago, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
              <% end %>
          <% else %>
            <td><%= link_to 'Ver', formas_de_pago, class: "btn btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if usuario_signed_in? %>
    <% if Usuario.last.role_id == 2 %>
      <%= link_to 'Nueva Formas de Pago', new_formas_de_pago_path, class: "btn btn-info" %>
    <% end %>
  <% end %>
</div>

app/views/formas_de_pagos/new.html.erb
<div class="container">
	<h1>Ingresar Formas De Pago</h1>

	<%= render 'form', formas_de_pago: @formas_de_pago %>

	<div class="form-group ">
		<%= link_to 'Atrás', formas_de_pagos_path, class: "btn btn-primary" %>	
	</div>
</div>

app/views/formas_de_pagos/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Nombre:</strong>
	  <%= @formas_de_pago.nombre %>
	</p>

	<%= link_to 'Editar', edit_formas_de_pago_path(@formas_de_pago), class: "btn btn-default" %> |
	<%= link_to 'Atrás', formas_de_pagos_path, class: "btn btn-danger" %>
</div>