config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  resources :quotes
  resources :componentes_plans
  resources :atributos_componentes
  resources :images
  resources :atributos
  resources :tipo_atributos
  resources :componentes
  resources :sedes
  resources :conditions
  resources :formas_de_pagos
  resources :components
  resources :constructions
  resources :locations
  resources :supports
  resources :espacios
  resources :burial_services
  resources :anforas
  resources :servicio_de_cinerarios
  resources :traslados
  resources :velatorios
  resources :urnas
  resources :directions
  resources :plans
  resources :conditions
  resources :tipo_clientes
  resources :type_plans
  resources :publications
  resources :type_publications
  resources :roles
  resources :servicios
  resources :componentes
  resources :caracteristicas
  resources :telefonos
  resources :tipo_empresas
  resources :comunas
  resources :regions
  resources :empresas
  devise_for :usuarios, :controllers => { :registrations => 'registrations'}
  resources :usuario, :controller => "usuario"
  get '/usuarios/new'


  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anfora.rb
class Anfora < ApplicationRecord
end

app/models/atributo.rb
class Atributo < ApplicationRecord
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :urna
  belongs_to :velatorio
  belongs_to :traslado
  belongs_to :servicio_de_cinerario
  belongs_to :anfora
  belongs_to :burial_service
  belongs_to :espacio
  belongs_to :construction
  belongs_to :location
  belongs_to :support
  belongs_to :plan
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  belongs_to :region
  has_many :sedes
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :plan
end

app/models/contacto.rb
class Contacto < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	belongs_to :tipo_empresa
	has_many :plans
	has_many :sedes
	belongs_to :usuario

	has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/espacio.rb
class Espacio < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :componente
  belongs_to :plan

  has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :servicio, optional: true
  belongs_to :type_plan
  belongs_to :tipo_cliente
  belongs_to :empresa
  has_many :componentes_plans
  has_many :componentes
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :plan
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/sede.rb
class Sede < ApplicationRecord
  belongs_to :empresa
  belongs_to :comuna
end

app/models/servicio.rb
class Servicio < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
  belongs_to :sede
end

app/models/traslado.rb
class Traslado < ApplicationRecord
end

app/models/urna.rb
class Urna < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessible :name, :apellido, :email, :password, :password_confirmation, :remember_me, :role_id
  belongs_to :role

end

app/controllers/urnas_controller.rb
class UrnasController < ApplicationController
  before_action :set_urna, only: [:show, :edit, :update, :destroy]

  # GET /urnas
  # GET /urnas.json
  def index
    @urnas = Urna.all
  end

  # GET /urnas/1
  # GET /urnas/1.json
  def show
  end

  # GET /urnas/new
  def new
    @urna = Urna.new
  end

  # GET /urnas/1/edit
  def edit
  end

  # POST /urnas
  # POST /urnas.json
  def create
    @urna = Urna.new(urna_params)

    respond_to do |format|
      if @urna.save
        format.html { redirect_to @urna, notice: 'Urna was successfully created.' }
        format.json { render :show, status: :created, location: @urna }
      else
        format.html { render :new }
        format.json { render json: @urna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urnas/1
  # PATCH/PUT /urnas/1.json
  def update
    respond_to do |format|
      if @urna.update(urna_params)
        format.html { redirect_to @urna, notice: 'Urna was successfully updated.' }
        format.json { render :show, status: :ok, location: @urna }
      else
        format.html { render :edit }
        format.json { render json: @urna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urnas/1
  # DELETE /urnas/1.json
  def destroy
    @urna.destroy
    respond_to do |format|
      format.html { redirect_to urnas_url, notice: 'Urna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_urna
      @urna = Urna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def urna_params
      params.require(:urna).permit(:modelo, :medida, :material, :terminacion, :color)
    end
end

app/helpers/urnas_helper.rb
module UrnasHelper
end

app/views/urnas/_form.html.erb
<%= form_for(urna) do |f| %>
  <% if urna.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this urna from being saved:</h2>

      <ul>
      <% urna.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form role="form"> 

    <div class="form-group">
    <%= f.label :modelo, "Modelo" %>
    <%= f.text_field :modelo, class:"form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :medida, "Medida:" %>
      <%= f.text_field :medida, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :material, "Material:" %>
      <%= f.text_field :material, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :terminacion, "Terminación:" %>
      <%= f.text_field :terminacion, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :color, "Color:" %>
      <%= f.text_field :color, class:"form-control" %>
    </div>


    <div class="actions">
      <%= f.submit "Crear Urna", :class => "btn btn-success" %>
    </div>    
  </form>

  <% end %>

app/views/urnas/edit.html.erb
<div class="container">
	<h1>Editando Urna</h1>

	<%= render 'form', urna: @urna %>

	<%= link_to 'Ver', @urna, class: "btn btn-default" %>
	<%= link_to 'Atrás', urnas_path, class: "btn btn-danger" %>
</div>

app/views/urnas/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Urnas</h1>

  <table>
    <thead>
      <tr>
        <th>Modelo</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Medida</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Material</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Terminacion</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Color</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @urnas.each do |urna| %>
        <tr>
          <td><%= urna.modelo %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= urna.medida %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= urna.material %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= urna.terminacion %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= urna.color %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <% if usuario_signed_in? %>
              <% if Usuario.last.role_id == 2 %>
                <td><%= link_to 'Ver', urna, class: "btn btn-primary" %></td>
                <td><%= link_to 'Editar', edit_urna_path(urna), class: "btn btn-success" %></td>
                <td><%= link_to 'Eliminar', urna, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
              <% end %>
          <% else %>
            <td><%= link_to 'Ver', urna, class: "btn btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if usuario_signed_in? %>
    <% if Usuario.last.role_id == 2 %>
      <%= link_to 'Nueva Urna', new_urna_path, class: "btn btn-info" %>
    <% end %>
  <% end %>
</div>

app/views/urnas/new.html.erb
<div class="container">
	<h1>Ingresar Urna</h1>
	<%= render 'form', urna: @urna %>
	<div class="form-group">
		<%= link_to 'Atrás', urnas_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/urnas/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Modelo:</strong>
    <%= @urna.modelo %>
  </p>

  <p>
    <strong>Medida:</strong>
    <%= @urna.medida %>
  </p>

  <p>
    <strong>Material:</strong>
    <%= @urna.material %>
  </p>

  <p>
    <strong>Terminacion:</strong>
    <%= @urna.terminacion %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= @urna.color %>
  </p>

  <br>

  <p>
  <strong>Seleccione otro componente que desea agregar al plan:</strong>
  </p>


  <div class="form-group">
    <%= link_to "Velatorio", {controller: "velatorios", action: "new"}, class: "btn btn-primary"%>
    <%= link_to "Traslado", {controller: "traslados", action: "new"}, class: "btn btn-success"%>
  </div>


  <br>
      

  <%= link_to 'Editar', edit_urna_path(@urna), class: "btn btn-default" %>
  <%= link_to 'Atrás', urnas_path, class: "btn btn-danger" %>

</div>