config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  resources :quotes
  resources :componentes_plans
  resources :atributos_componentes
  resources :images
  resources :atributos
  resources :tipo_atributos
  resources :componentes
  resources :sedes
  resources :conditions
  resources :formas_de_pagos
  resources :components
  resources :constructions
  resources :locations
  resources :supports
  resources :espacios
  resources :burial_services
  resources :anforas
  resources :servicio_de_cinerarios
  resources :traslados
  resources :velatorios
  resources :urnas
  resources :directions
  resources :plans
  resources :conditions
  resources :tipo_clientes
  resources :type_plans
  resources :publications
  resources :type_publications
  resources :roles
  resources :servicios
  resources :componentes
  resources :caracteristicas
  resources :telefonos
  resources :tipo_empresas
  resources :comunas
  resources :regions
  resources :empresas
  devise_for :usuarios, :controllers => { :registrations => 'registrations'}
  resources :usuario, :controller => "usuario"
  get '/usuarios/new'


  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anfora.rb
class Anfora < ApplicationRecord
end

app/models/atributo.rb
class Atributo < ApplicationRecord
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :urna
  belongs_to :velatorio
  belongs_to :traslado
  belongs_to :servicio_de_cinerario
  belongs_to :anfora
  belongs_to :burial_service
  belongs_to :espacio
  belongs_to :construction
  belongs_to :location
  belongs_to :support
  belongs_to :plan
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  belongs_to :region
  has_many :sedes
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :plan
end

app/models/contacto.rb
class Contacto < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	belongs_to :tipo_empresa
	has_many :plans
	has_many :sedes
	belongs_to :usuario

	has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/espacio.rb
class Espacio < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :componente
  belongs_to :plan

  has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :servicio, optional: true
  belongs_to :type_plan
  belongs_to :tipo_cliente
  belongs_to :empresa
  has_many :componentes_plans
  has_many :componentes
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :plan
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/sede.rb
class Sede < ApplicationRecord
  belongs_to :empresa
  belongs_to :comuna
end

app/models/servicio.rb
class Servicio < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
  belongs_to :sede
end

app/models/traslado.rb
class Traslado < ApplicationRecord
end

app/models/urna.rb
class Urna < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessible :name, :apellido, :email, :password, :password_confirmation, :remember_me, :role_id
  belongs_to :role

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]


  # GET /plans
  # GET /plans.json

  def index
     @q = params[:q]
    if @q
      @plans = Plan.where(:servicio_id => @q)
    else
      @plans = Plan.all
     end




  end

  # GET /plans/1
  # GET /plans/1.json
  def show
     @id = params[:id]
    if @id
      @plans = Plan.where(:servicio_id => @id)
    else
      @plans = Plan.all
     end

  end

  # GET /plans/new
  def new
    @plan = Plan.new
    @type_plans = TypePlan.all 
    @tipo_clientes = TipoCliente.all
    @empresas = Empresa.all
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_parent_for(comuna)
    select(:comuna, :id, Comuna.all.collect{|c| [c.nombre, c.id]} ) # <--- mistake!
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:nombre, :codigo, :precio, :empresa_id,  :servicio_id, :type_plan_id, :tipo_cliente_id, :state, :necesidad)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form role="form">

    <div class="form-group">
      <%= f.label :nombre, "Nombre de Plan:" %>
      <%= f.text_field :nombre, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :codigo, "Codigo:" %>
      <%= f.number_field :codigo, class:"form-control", placeholder:"Pendiente" %>
    </div>

    <div class="form-group">
    <label>Nombre Funeraria:</label>
    <%= f.collection_select :empresa_id, Empresa.all, :id, :nombre, {prompt: true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
    <label>Tipo de Plan:</label>
    <%= f.collection_select :type_plan_id, TypePlan.all, :id, :nombre, {prompt: true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
    <label>Tipo de Cliente:</label>
    <%= f.collection_select :tipo_cliente_id, TipoCliente.all, :id, :nombre, {prompt: true}, {class: "form-control"} %>
    </div>

    <div class="form-group">
    <label>Servicio:</label>
    <%= f.collection_select :servicio_id, Servicio.all, :id, :nombre, {prompt: true}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= f.label :precio, "Precio:" %>
      <%= f.number_field :precio, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.check_box :state %>
      <%= f.label :state, "Listo para Publicar" %>
    </div>

    <div class="form-group">
      <%= f.check_box :necesidad %>
      <%= f.label :necesidad, "Necesidad Inmediata" %>
    </div>


    <div class="actions">
      <%= f.submit "Crear Plan", :class => "btn btn-success" %>
    </div>    
  </form>

  <% end %>

  

app/views/plans/edit.html.erb
<div class="container">
	<h1>Editando Plan</h1>

	<%= render 'form', plan: @plan %>

	<%= link_to 'Ver', @plan, class: "btn btn-default" %>
	<% if @plan.servicio.id == 8 %>
			<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(8).id}, class: "btn btn-danger"%>
		<% elsif @plan.servicio.id == 6 %>
				<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(6).id}, class: "btn btn-danger"%>
			<% elsif @plan.servicio.id == 7 %>
					<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(7).id}, class: "btn btn-danger"%>
				<% elsif @plan.servicio.id == 1 %>
						<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(1).id}, class: "btn btn-danger"%>
	<% end %>
</div>

app/views/plans/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

<div class="container col-md-3 pull-left">
    <div class="row">
    <div class="col-xs-12">
      <div id="accordion" class="panel panel-primary behclick-panel">
        <div class="panel-heading">
          <h3 class="panel-title">Realice su busqueda</h3>
        </div>
        <div class="panel-body" >
          <div class="panel-heading " >
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse0">
                <i class="indicator fa fa-caret-down" aria-hidden="true"></i> Localidad
              </a>
            </h4>
          </div>
          <div id="collapse0" class="panel-collapse collapse in" >
            <ul class="list-group">

              <li class="list-group-item">
                <div class="checkbox">
                  Comuna:
                  <form>
                  <div>
                    <%= select("comuna", "id", Comuna.pluck(:nombre)) %>
                  </div>
                    
                    
                    <%= link_to 'Buscar', {controller: "/comunas", action: "show", id: 2 }, class: "btn btn-primary" %>
                  </form>

                  Región:
                  <form>
                  <div>
                    <%= select("region", "id", Region.pluck(:nombre)) %>
                  </div>
                    
                    
                    <%= link_to 'Buscar', {controller: "/regions", action: "show", id: 2 }, class: "btn btn-primary" %>
                  </form>
                  
                </div>
              </li>
      
            </ul>
          </div>

          <div class="panel-heading " >
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse1">
                <i class="indicator fa fa-caret-down" aria-hidden="true"></i> Necesidad
              </a>
            </h4>
          </div>
          <div id="collapse1" class="panel-collapse collapse in" >
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" value="">
                    Necesidad Inmediata
                  </label>
                </div>
              </li>
              <li class="list-group-item">
                <div class="checkbox" >
                  <label>
                    <input type="checkbox" value="">
                    Compra Anticipada
                  </label>
                </div>
              </li>
            </ul>
          </div>
          <div class="panel-heading" >
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse3"><i class="indicator fa fa-caret-down" aria-hidden="true"></i> Tipo de Empresa</a>
            </h4>
          </div>
          <div id="collapse3" class="panel-collapse collapse in">
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  Empresa:
                  <form>
                  <div>
                    <%= select("empresa", "id", Empresa.pluck(:nombre)) %>
                  </div>
                    
                    
                    <%= link_to 'Buscar', {controller: "/empresas", action: "show", id: 2 }, class: "btn btn-primary" %>
                  </form>                  
                </div>
              </li>
            </ul>
          </div>
          <div class="panel-heading" >
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse3"><i class="indicator fa fa-caret-down" aria-hidden="true"></i> Tipo de Plan</a>
            </h4>
          </div>
          <div id="collapse3" class="panel-collapse collapse in">
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label>
                    <input type="checkbox" value="">
                    Basico
                  </label>
                </div>
              </li>
              <li class="list-group-item">
                <div class="checkbox" >
                  <label>
                    <input type="checkbox" value="">
                    Medio
                  </label>
                </div>
              </li>
              <li class="list-group-item">
                <div class="checkbox" >
                  <label>
                    <input type="checkbox" value="">
                    Superior
                  </label>
                </div>
              </li>
            </ul>
          </div>
          <div class="panel-heading" >
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse2"><i class="indicator fa fa-caret-right" aria-hidden="true"></i> Codigo del Plan</a>
            </h4>
          </div>
          <div id="collapse2" class="panel-collapse collapse">
            <ul class="list-group">
              <li class="list-group-item">
                <div class="checkbox">
                  <label>
                    Codigo:
                    <input type="text-field" value="">
                    
                  </label>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container col-md-9 pull-right">
  <p id="notice"><%= notice %></p>
  
  <h1>Planes
  <% if @q == "8" %>
      Funerarios
    <% elsif @q == "6" %>
        Crematorios
      <% elsif @q == "7" %>
          Sepulturas
        <% elsif @q == "1" %>
            Servicios de Sepultación
  <% end %>
  </h1>

  <table>

    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <% if plan.state == true %>
        <div class="panel panel-primary">
          <div class="row">
                <div class="col-md-12">
                    <div class="thumbnail">
                        <div class="caption">
                              <div class="group list-group-image pull-left" alt="" />
                                    <%= image_tag plan.empresa.cover.url(:minimum) %>:
                              </div>

                            <div class="container">
                              <h4 class="group inner list-group-item-heading">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nombre del Plan:</h4>   
                              <p class="group inner list-group-item-text">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= plan.nombre %></p>
                                <br>      
                              <h4 class="group inner list-group-item-heading">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Empresa:</h4>
                              <p class="group inner list-group-item-text">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= plan.empresa.nombre %></p>
                                <br>
                              <h4 class="group inner list-group-item-heading">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tipo Plan:</h4>
                              <p class="group inner list-group-item-text">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= plan.type_plan.nombre %></p>
                                <br>
                              <% plan.empresa.sedes.each do |plan_empresa_sedes| %>  
                              <h4 class="group inner list-group-item-heading">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Localidad:</h4>
                              <p class="group inner list-group-item-text">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= plan_empresa_sedes.comuna.nombre %> | <%= plan_empresa_sedes.comuna.region.nombre %></p>
                                <br>
                              <% end %>
                            
                              <p class="group inner list-group-item-text">
                                <% if plan.necesidad == true %></p>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Necesidad Inmediata
                                <% else %>
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Compra Anticipada
                                <% end %>
                                <br> 
                              <% if usuario_signed_in? %>
                                <% if Usuario.last.role_id == 2 %>
                                    <h4 class="group inner list-group-item-heading">
                                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Publicado:</h4>
                                    <p class="group inner list-group-item-text">
                                    <% if plan.state == true %></p>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Publicado
                                    <% else %>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pendiente
                                    <% end %>
                                      <br>
                                <% end %>
                              <% end %>   
                            </div>
                            
                            

                                                  
                            <div class="row">
                            <div class="col-xs-3">
                              <br>
                              <br>
                              <br>
                              <br>
                              <%= link_to 'Me interesa', {controller: "/quotes", action: "new", id: plan.id}, class: "btn btn-lg btn-success" %>
                            </div>
                            <div class="col-xs-3 pull-right">
                              <div class="panel panel-success">
                                  <div class="panel-body text-center">
                                      <h1>$<%= number_with_delimiter(plan.precio, delimiter: ".")  %></h1><h4>con IVA Incluido</h4>
                                      <div class="col-md-12 text-center">
                                      <% if usuario_signed_in? %>
                                          <% if Usuario.last.role_id == 2 %>
                                            <%= link_to 'Ver Plan', plan, class: "btn btn-primary" %>
                                            <%= link_to 'Editar', edit_plan_path(plan), class: "btn btn-success" %>
                                            <%= link_to 'Eliminar', plan, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
                                          <% end %>
                                      <% else %>
                                        <%= link_to 'Ver Plan', plan, class: "btn btn-primary" %>
                                        </div>
                                      <% end %>  
                                  </div>
                              </div>
                              
                          </div>
                           
                      </div>

                        </div>
                    </div>
                </div>
          </div> 
        </div>
   
        <% end %>
        </tr>
      <% end %>  
      

      
    </tbody>
    
  </table>

  

  <br>
  <% if usuario_signed_in? %>
    <% if Usuario.last.role_id == 2 %>
      <%= link_to 'Nuevo Plan', new_plan_path, class: "btn btn-info" %>
    <% end %>
  <% end %>
</div>

app/views/plans/new.html.erb
<div class="container">
	<h1>Ingresar Plan</h1>
	<%= render 'form', plan: @plan %>
	<div class="form-group ">
		<%= link_to 'Atrás', plans_path, class: "btn btn-primary" %>
	</div>
	
</div>

app/views/plans/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Precio:</strong>
	  <%= @plan.precio %>
	</p>

	<strong>Nombre Funeraria:</strong>
	  <%= @plan.empresa.nombre %>
	</p>
	<p>
	<% @plan.empresa.sedes.each do |plan_empresas| %>
        <tr>
        <strong>Localidad :</strong>
     	<%= plan_empresas.comuna.nombre %> |
     	<%= plan_empresas.comuna.region.nombre %>
          
        </tr>
      <% end %>
    </p>
	<p>
	  <strong>Nombre del Plan:</strong>
	  <%= @plan.nombre %>
	</p>

	<strong>Tipo de Plan:</strong>
	  <%= @plan.type_plan.nombre %>
	</p>

	<strong>Tipo de Cliente:</strong>
	  <%= @plan.tipo_cliente.nombre %>
	</p>

	<p>
	  <strong>Codigo:</strong>
	  <%= @plan.codigo %>
	</p>

	<p>
	<strong>Servicio:</strong>
	  <%= @plan.servicio.nombre %>
	  <br>
	</p>

	<p>
	  <% @plan.componentes_plans.each do |plan_componente| %>
        <tr>
     <div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title"><%= plan_componente.componente.nombre %></h3>
			<span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
		</div>
		<div class="panel-body">
          <p>
			<strong>Atributos:</strong>
			<br>
			  <% plan_componente.componente.atributos_componentes.each do |plan_componente_atributos_componentes| %>
		        <tr>
		          <td><%= plan_componente_atributos_componentes.atributo.nombre %></td>:
		          <td><%= plan_componente_atributos_componentes.atributo.valor %></td>
		          <br>
		        </tr>
		      <% end %>
		  </p>
		  <p>
			<strong>Imagen:</strong>
			<br>
			  <% plan_componente.componente.images.each do |plan_componente_images| %>
		        <tr>
		          <td><%= image_tag plan_componente_images.cover.url(:minimum) %></td>:
		          <br>
		        </tr>
		      <% end %>
		  </p>
          <br>
          <% if usuario_signed_in? %>
	  		<% if Usuario.last.role_id == 2 %>
          		<td><%= link_to 'Ver', {controller: "/componentes", action: "show", id: Componente.find(plan_componente.componente).id}, class: "btn btn-primary" %></td>
	          <% end %>
		<% end %>
          <br>
		</div>
	</div>
          
        </tr>
      <% end %>
	</p>

	<p>
	<strong>Necesidad:</strong>
	  <% if @plan.necesidad == true %>
	  	Necesidad Inmediata
	  <% else %>
	  	Compra Anticipada	
	  <% end %>
	  <br>
	</p>

	<p>
		<% if usuario_signed_in? %>
		  <% if Usuario.last.role_id == 2 %>
		  	<strong>Publicado:</strong>
		    <%= @plan.state %>
		  <% end %>
		<% end %>
	</p>

	<p>
	


	<br>
			
	<% if usuario_signed_in? %>
	  <% if Usuario.last.role_id == 2 %>
	    <%= link_to 'Editar', edit_plan_path(@plan), class: "btn btn-default" %>
	  <% end %>
	<% end %>
	
	<%= link_to 'Me interesa', {controller: "/quotes", action: "new", id: Plan.find(params[:id])}, class: "btn btn-primary" %>

	<% if @plan.servicio.id == 8 %>
			<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(8).id}, class: "btn btn-danger"%>
		<% elsif @plan.servicio.id == 6 %>
				<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(6).id}, class: "btn btn-danger"%>
			<% elsif @plan.servicio.id == 7 %>
					<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(7).id}, class: "btn btn-danger"%>
				<% elsif @plan.servicio.id == 1 %>
						<%= link_to "Atrás", {controller: "/plans", action: "index", q: Servicio.find(1).id}, class: "btn btn-danger"%>
	<% end %>

</div>