config/routes.rb
Rails.application.routes.draw do
  resources :contactos
  resources :quotes
  resources :componentes_plans
  resources :atributos_componentes
  resources :images
  resources :atributos
  resources :tipo_atributos
  resources :componentes
  resources :sedes
  resources :conditions
  resources :formas_de_pagos
  resources :components
  resources :constructions
  resources :locations
  resources :supports
  resources :espacios
  resources :burial_services
  resources :anforas
  resources :servicio_de_cinerarios
  resources :traslados
  resources :velatorios
  resources :urnas
  resources :directions
  resources :plans
  resources :conditions
  resources :tipo_clientes
  resources :type_plans
  resources :publications
  resources :type_publications
  resources :roles
  resources :servicios
  resources :componentes
  resources :caracteristicas
  resources :telefonos
  resources :tipo_empresas
  resources :comunas
  resources :regions
  resources :empresas
  devise_for :usuarios, :controllers => { :registrations => 'registrations'}
  resources :usuario, :controller => "usuario"
  get '/usuarios/new'


  root 'welcome#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anfora.rb
class Anfora < ApplicationRecord
end

app/models/atributo.rb
class Atributo < ApplicationRecord
end

app/models/component.rb
class Component < ApplicationRecord
  belongs_to :urna
  belongs_to :velatorio
  belongs_to :traslado
  belongs_to :servicio_de_cinerario
  belongs_to :anfora
  belongs_to :burial_service
  belongs_to :espacio
  belongs_to :construction
  belongs_to :location
  belongs_to :support
  belongs_to :plan
end

app/models/comuna.rb
class Comuna < ApplicationRecord
  belongs_to :region
  has_many :sedes
end

app/models/contacto.rb
class Contacto < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	belongs_to :tipo_empresa
	has_many :plans
	has_many :sedes
	belongs_to :usuario

	has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/espacio.rb
class Espacio < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :componente
  belongs_to :plan

  has_attached_file :cover, styles: {medium: "1280x720", thumb:"800x400", minimum:"400x200"}
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :servicio, optional: true
  belongs_to :type_plan
  belongs_to :tipo_cliente
  belongs_to :empresa
  has_many :componentes_plans
  has_many :componentes
  has_many :quotes
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :plan
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/sede.rb
class Sede < ApplicationRecord
  belongs_to :empresa
  belongs_to :comuna
end

app/models/servicio.rb
class Servicio < ApplicationRecord
	belongs_to :tipo_empresa
end

app/models/servicio_de_cinerario.rb
class ServicioDeCinerario < ApplicationRecord
end

app/models/support.rb
class Support < ApplicationRecord
end

app/models/telefono.rb
class Telefono < ApplicationRecord
  belongs_to :sede
end

app/models/traslado.rb
class Traslado < ApplicationRecord
end

app/models/urna.rb
class Urna < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessible :name, :apellido, :email, :password, :password_confirmation, :remember_me, :role_id
  belongs_to :role

end

app/controllers/servicio_de_cinerarios_controller.rb
class ServicioDeCinerariosController < ApplicationController
  before_action :set_servicio_de_cinerario, only: [:show, :edit, :update, :destroy]

  # GET /servicio_de_cinerarios
  # GET /servicio_de_cinerarios.json
  def index
    @servicio_de_cinerarios = ServicioDeCinerario.all
  end

  # GET /servicio_de_cinerarios/1
  # GET /servicio_de_cinerarios/1.json
  def show
  end

  # GET /servicio_de_cinerarios/new
  def new
    @servicio_de_cinerario = ServicioDeCinerario.new
  end

  # GET /servicio_de_cinerarios/1/edit
  def edit
  end

  # POST /servicio_de_cinerarios
  # POST /servicio_de_cinerarios.json
  def create
    @servicio_de_cinerario = ServicioDeCinerario.new(servicio_de_cinerario_params)

    respond_to do |format|
      if @servicio_de_cinerario.save
        format.html { redirect_to @servicio_de_cinerario, notice: 'Servicio de cinerario was successfully created.' }
        format.json { render :show, status: :created, location: @servicio_de_cinerario }
      else
        format.html { render :new }
        format.json { render json: @servicio_de_cinerario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicio_de_cinerarios/1
  # PATCH/PUT /servicio_de_cinerarios/1.json
  def update
    respond_to do |format|
      if @servicio_de_cinerario.update(servicio_de_cinerario_params)
        format.html { redirect_to @servicio_de_cinerario, notice: 'Servicio de cinerario was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio_de_cinerario }
      else
        format.html { render :edit }
        format.json { render json: @servicio_de_cinerario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicio_de_cinerarios/1
  # DELETE /servicio_de_cinerarios/1.json
  def destroy
    @servicio_de_cinerario.destroy
    respond_to do |format|
      format.html { redirect_to servicio_de_cinerarios_url, notice: 'Servicio de cinerario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio_de_cinerario
      @servicio_de_cinerario = ServicioDeCinerario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_de_cinerario_params
      params.require(:servicio_de_cinerario).permit(:capilla, :sala_de_velatorio, :podium, :liturgia, :amplificacion, :diacono, :coro, :cafeteria, :ceremonia_entre_cenizas, :anfora_incluida)
    end
end

app/helpers/servicio_de_cinerarios_helper.rb
module ServicioDeCinerariosHelper
end

app/views/servicio_de_cinerarios/_form.html.erb
<%= form_for(servicio_de_cinerario) do |f| %>
<% if servicio_de_cinerario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servicio_de_cinerario.errors.count, "error") %> prohibited this servicio_de_cinerario from being saved:</h2>

      <ul>
      <% servicio_de_cinerario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container">
    <form role="form">
      <div class="form-group">
          <%= f.check_box :capilla, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :capilla, 'Capilla' %> 
      </div>
      <div class="form-group">
          <%= f.check_box :sala_de_velatorio, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :sala_de_velatorio, 'Sala de Velatorio' %>
      </div>
      <div class="form-group">
        <%= f.check_box :podium, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :podium, 'Podium' %>
      </div>
      <div class="form-group">
        <%= f.check_box :liturgia, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :liturgia, 'Liturgía' %>
      </div>
      <div class="form-group">
        <%= f.check_box :amplificacion, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :amplificacion, 'Amplificación' %>
      </div>
      <div class="form-group">
        <%= f.check_box :diacono, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :diacono, 'Diacono' %>
      </div>
      <div class="form-group">
        <%= f.label :coro, "Coro:" %>
        <%= f.number_field :coro, class:"form-control" %>
      </div>
        <div class="form-group">
        <%= f.label :cafeteria, "Cafeteria:" %>
        <%= f.text_field :cafeteria, class:"form-control" %>
      </div>
        <div class="form-group">
        <%= f.check_box :ceremonia_entre_cenizas, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :ceremonia_entre_cenizas, 'Ceremonia entrega Cenizas' %>
      </div>
       <div class="form-group">
        <%= f.check_box :anfora_incluida, :checked => false %>
        <a> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;</a>
        <%= label :anfora_incluida, 'Anfora Incluida' %>
      </div>
      <div class="actions">
        <%= f.submit "Crear Servicio de Cinerario", :class => "btn btn-success" %>
      </div> 
    </form>
  </div>


<% end %>

app/views/servicio_de_cinerarios/edit.html.erb
<div class="container">
	<h1>Editando Servicio De Cinerario</h1>

	<%= render 'form', servicio_de_cinerario: @servicio_de_cinerario %>

	<%= link_to 'Ver', @servicio_de_cinerario, class: "btn btn-default" %>
	<%= link_to 'Atrás', servicio_de_cinerarios_path, class: "btn btn-danger" %>
</div>

app/views/servicio_de_cinerarios/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Servicio De Cinerarios</h1>

  <table>
    <thead>
      <tr>
        <th>Capilla</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Sala de velatorio</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Podium</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Liturgia</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Amplificacion</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Diacono</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Coro</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Cafeteria</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Ceremonia entre cenizas</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Anfora incluida</th>
        <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @servicio_de_cinerarios.each do |servicio_de_cinerario| %>
        <tr>
          <td><%= servicio_de_cinerario.capilla %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.sala_de_velatorio %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.podium %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.liturgia %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.amplificacion %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.diacono %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.coro %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.cafeteria %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.ceremonia_entre_cenizas %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <td><%= servicio_de_cinerario.anfora_incluida %></td>
          <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
          <% if usuario_signed_in? %>
              <% if Usuario.last.role_id == 2 %>
                <td><%= link_to 'Ver', servicio_de_cinerario, class: "btn btn-primary" %></td>
                <td><%= link_to 'Editar', edit_servicio_de_cinerario_path(servicio_de_cinerario), class: "btn btn-success" %></td>
                <td><%= link_to 'Eliminar', servicio_de_cinerario, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
              <% end %>
          <% else %>
            <td><%= link_to 'Ver', servicio_de_cinerario, class: "btn btn-primary" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if usuario_signed_in? %>
    <% if Usuario.last.role_id == 2 %>
      <%= link_to 'Nuevo Servicio de Cinerario', new_servicio_de_cinerario_path, class: "btn btn-info" %>
    <% end %>
  <% end %>
</div>

app/views/servicio_de_cinerarios/new.html.erb
<div class="container">
  	<h1>Ingresar Servicio De Cinerario</h1>

	<%= render 'form', servicio_de_cinerario: @servicio_de_cinerario %>

	<div class="form-group ">
	<%= link_to 'Atrás', servicio_de_cinerarios_path, class: "btn btn-primary" %>	
</div>
</div>

app/views/servicio_de_cinerarios/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Capilla:</strong>
    <%= @servicio_de_cinerario.capilla %>
  </p>

  <p>
    <strong>Sala de velatorio:</strong>
    <%= @servicio_de_cinerario.sala_de_velatorio %>
  </p>

  <p>
    <strong>Podium:</strong>
    <%= @servicio_de_cinerario.podium %>
  </p>

  <p>
    <strong>Liturgia:</strong>
    <%= @servicio_de_cinerario.liturgia %>
  </p>

  <p>
    <strong>Amplificacion:</strong>
    <%= @servicio_de_cinerario.amplificacion %>
  </p>

  <p>
    <strong>Diacono:</strong>
    <%= @servicio_de_cinerario.diacono %>
  </p>

  <p>
    <strong>Coro:</strong>
    <%= @servicio_de_cinerario.coro %>
  </p>

  <p>
    <strong>Cafeteria:</strong>
    <%= @servicio_de_cinerario.cafeteria %>
  </p>

  <p>
    <strong>Ceremonia entre cenizas:</strong>
    <%= @servicio_de_cinerario.ceremonia_entre_cenizas %>
  </p>

  <p>
    <strong>Anfora incluida:</strong>
    <%= @servicio_de_cinerario.anfora_incluida %>
  </p>

  <br>

  <p>
    <strong>Seleccione otro componente que desea agregar al plan:</strong>
  </p>


  <div class="form-group">
    <%= link_to "Anforas", {controller: "anforas", action: "new"}, class: "btn btn-primary"%>
  </div>


  <br>
        

  <%= link_to 'Editar', edit_servicio_de_cinerario_path(@servicio_de_cinerario), class: "btn btn-default" %>
  <%= link_to 'Atrás', servicio_de_cinerario_path, class: "btn btn-danger" %>
</div>